info:
  app:
    name: DirectoryLookupService
    description: Directory Lookup Service
    version: 1.0.0

dirservice:
  supportLookupList:
    - carriers
    - cities
    - passengertypes
    - currencies
  rolesList:
    - NMV_INQUIRY
    - INHOUSE_USER  

logging:
    file: /opt/fme/log/directory-lookup-service.log
    level:
        org.springframework: 'INFO'
        
spring.jmx:
  enabled: false